### ISSUE TITLE
french probleme when translated

### ISSUE THREAD

**Issue by DanielAbsi** [tetsuwo/website-blocker-chrome.ext#102]
Hi I downloasd the extention in french and I saw that in french thare is some plases still in english I would like to translate them. thanks you

**Comment by tetsuwo** [comment]
@DanielAbsi 
thanks for your commenting :)

please you translate the tab "fr" of this spreadsheet.
https://docs.google.com/spreadsheets/d/1CipI3lnyBWU_vUSwOvInlHlsech0FS3pwn4zBZSmp5M/edit#gid=1582512836

thanks!

**Comment by DanielAbsi** [comment]
Hi tetsuwo, at the ligne 26 (Input), the french verison is writing input but input is in English, an if french It doesn't have a specific term. Do you have a photo of ware the input is writing.

**Comment by DanielAbsi** [comment]
Hi I finished translating the french files and you can update your chrome extension.

**Comment by tetsuwo** [comment]
@DanielAbsi thank you :)

**Comment by tetsuwo** [comment]
@DanielAbsi 
thanks for your translate :)
i released now!
https://chrome.google.com/webstore/detail/website-blocker-beta/hclgegipaehbigmbhdpfapmjadbaldib
