### ISSUE TITLE
My Bro has a problem

### ISSUE THREAD

**Issue by shantanubdas311** [tetsuwo/website-blocker-chrome.ext#47]
This is not me, with this problem Im trying to report to you the problem that happened with this site to my bro. First of all at school he blocked facebook and youtube to avoid his distractions. He chose to block the site for 4 hours but as 4 hours passed, there was an error unblocking them again,

Thank You

**Comment by Libervurto** [comment]
@shantanubdas311 "just tell me how i can get rid of that bug", I can smell the entitlement from here.  Do you not think tetsuwo is trying to help?  Do you not think they might need the information from that link to be able to help and this is why they asked for it?  If you used your own brain cells you might have worked out that the link must be followed on the machine that is having the problems; it is a link to the options settings for the extension.
