### ISSUE TITLE
Bad spanish translation

### ISSUE THREAD

**Issue by brendaadlv** [tetsuwo/website-blocker-chrome.ext#61]
Hi! Please change the spanish translation of "please, support me" or " please, support us" since the one that you are using now "por favor, me apoyen!" sounds like you are desperately asking for someone to be behind you (if you know what I mean) and it is ungrammatical.

**Comment by tetsuwo** [comment]
Thanks for post.
What should I say? If you have any ideas , pls give me them!

**Comment by brendaadlv** [comment]
Hi! You should say something like "¡Por favor, colabora con nosotros!" if
you are a team since "nosotros" means "us" but if you are on your own or
you do not want to use "us" you can just say "¡Por favor, colabora!". Good
Luck!

2015-01-15 11:51 GMT-02:00 Tetsuwo OISHI <notifications@github.com>:
