### ISSUE TITLE
German

### ISSUE THREAD

**Issue by macw73** [tetsuwo/website-blocker-chrome.ext#68]
Hi,

great Tool. I took the time to check the german translation. Seel Below. Hope it helps

Markus

Webseite Blocher (Beta) Einstellung
Webseite Blocher (Beta) Einstellungen

Name: Why Website Blocher, not Blocker? 

Webseite Blocher ist nützlich, wenn Sie auf seine Arbeit konzentrieren wollen.
Webseite Blocher ist nützlich, wenn Sie sich auf Ihre Arbeit konzentrieren wollen.// Der Website blocher hilft ihnen, sich besser auf Ihre Arbeit zu konzentrieren.

Blocking Webseite
Webseiten blockieren

Websites zu blockieren
Zu blockierende Webseiten

Format:
OK

URL hhmm-hhmm,hhmm-hhmm
OK

Beispiel:
OK

Input:
Eingabe:

Day's of the week:
Wochentage:

 Sunday   Monday   Tuesday   Wednesday   Thursday   Friday   Saturday
 Sonntag    Montag  Dienstag    Mittwoch    Donnerstag  Freitag Samstag

Nachrichten, wann gesperrt
Nachrichten bei gesperrten Seiten / Gesperrt-Nachricht

Title bei blockierten
Titel bei blockierten Seiten

This page is blocked.
Diese Seite ist blockiert.

Meldung bei blockierten
Meldung bei blockierten Seiten

Kein Zugriff auf diese Seite.
Kein Zugriff auf diese Seite.

URL to redirect when blocked
URL zur Weiterleitung bei gesperrten Seiten.

EIN / AUS Funktionen jedes
Funktionen einzeln Ein- oder Ausschalten / Funktionen einzeln aktivieren

Basic Einstellungen
Basis Einstellungen

  Enable of the block function
  Blockier-Funktion aktivieren
  Enable of the time-group function (ex) 0000-2359 ...
  Zeitgesteuertes Blockieren aktivieren (z.B. 0000-2359 ...)
  Enable of shortcut link to the options page
  Link auf die Optionssite aktivieren
  Enable of each function control from popup page
  Steuerung jeder einzelnen Funktion im Popup-Fenster aktivieren

Kennwort
OK

Locked with password
Kennwortsperre

Thank you for waiting! 
Vielen Dank für's Warten!

Try the password-function now!
Probieren Sie die Passwort-Funktion jetzt aus!

  Enable of the password function
  Passwort-Funktion aktivieren

Revision History
Revisionsverlauf

sparen  
Speichern

Speichern und schließen
Speichern und Schließen

**Comment by tetsuwo** [comment]
@macw73 
thanks for your commenting :)
i modified it! (version 0.3.2)
