### ISSUE TITLE
no back button?

### ISSUE THREAD

**Issue by floydbeck** [tetsuwo/website-blocker-chrome.ext#95]
When a message comes out, showing a blocked website, there is no BACK button. I have to close the notification web page and reenter my search. A back button would help greatly, though not critical. Thanks.

**Comment by tetsuwo** [comment]
@floydbeck 
thanks for your comments :)

> A back button would help greatly, though not critical.

hmm...
certainly, it is very useful!
i will implements it in the future not far 👍

**Comment by tetsuwo** [comment]
@floydbeck 
i released new version extension implemented "back button" on blocked page 👍 
https://chrome.google.com/webstore/detail/website-blocker-beta/hclgegipaehbigmbhdpfapmjadbaldib
