### ISSUE TITLE
Provide this Wbsite Blocker in windows application using c++ driver

### ISSUE THREAD

**Issue by AkshayUsha** [tetsuwo/website-blocker-chrome.ext#98]
please Provide this Wbsite Blocker in windows application using c++ driver without host and windows source using using only personal firewall rules

**Comment by AkshayUsha** [comment]
please Provide this Wbsite Blocker in windows application using c++ driver without host and windows source using using only personal firewall rules

**Comment by tetsuwo** [comment]
@AkshayUsha 
it is so difficult... :( 
sorry
